USE `souvenir`;

DELIMITER $$

DROP TRIGGER IF EXISTS souvenir.SOUVENIRS_AFTER_UPDATE$$
USE `souvenir`$$
CREATE DEFINER = CURRENT_USER TRIGGER `souvenir`.`SOUVENIRS_AFTER_UPDATE` AFTER UPDATE ON `SOUVENIRS` FOR EACH ROW
BEGIN
	UPDATE SOUVENIRS_AUDIT SET last_update_datetime = now() WHERE souvenir_id = OLD.souvenir_id;
END$$
DELIMITER ;
