DROP PROCEDURE IF EXISTS souvenir.selectAllSouvenirs;
DELIMITER $$
CREATE DEFINER=`souvenir`@`localhost` PROCEDURE `selectAllSouvenirs`()
BEGIN
	SELECT * FROM FULL_SELECT_SOUVENIRS;
END$$
DELIMITER ;
